system:
  #是否重新刷新菜单
  isResetMenu: true 

server:
  port:8080
  address:localhost
spring:
  #HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false
 
mybatis:
  typeAliasesPackage: com.mur.domain.*.*
  mapperLocations: classpath:/com/mur/mapper/xml/*/*.xml
  
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.mur.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  #config-location: classpath:mybatis/mybatis-config.xml
logging:
  level:
    com.mur: DEBUG
